name: birds

channels:
  - pytorch
  - defaults
  - openbabel
  - rdkit
  - bioconda

dependencies:
  - torchvision=0.6.0
  - cudatoolkit=10.2
  - pytorch=1.5.0
  - matplotlib=3.2.1
  - jupyter=1.0.0
  - flake8=3.8.3
  - biopython=1.77
  - rdkit=2019.09.3
  - openbabel=3.1.1
  - aria2=1.34.0
  - scikit-learn=0.23.1
  - flask=1.1.2
  - pip=20.1.1
  - pip:
      - pytorch-lightning==0.8.5
      - torch-cluster==1.5.4
      - test-tube==0.7.5
      - black
