name: birds

channels:
  - pytorch
  - defaults
  - openbabel
  - rdkit
  - bioconda

dependencies:
  - cudatoolkit=10.2
  - pytorch=1.5.0
  - torchvision=0.6.0
  - matplotlib
  - jupyter
  - flake8
  - biopython=1.77
  - rdkit=2019.09.3
  - openbabel
  - aria2
  - scikit-learn=0.23.1
  - flask
  - pip
  - pip:
      - pytorch-lightning==0.8.5
      - test-tube==0.7.5
      - black
